configuration: Release

build:
  project: AppVeyorTest.sln
  verbosity: detailed

cache:
  - packages -> **\packages.config

artifacts:
  - path: ..\..\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll